# This is a basic workflow to help you get started with Actions

name: "Search and output issues"
on:
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    - name: Query Issues Output
      uses: christothes/IssueOutputAction@v1.1
      with:
        # The github API token, if not he default
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        # 
        repoOwnerAndName: 'Azure/azure-sdk-for-net'
        # A query to search for Issues. See https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests
        searchquery: 'tables is:open' 
        # Filters queried Issues to those associated with Milestones in a given state: <open|closed|all> .
        searchByAssociatedMilestoneState: 'open' 
